### ISSUE TITLE
Warning: Calling fails_with :llvm is deprecated!

### ISSUE THREAD

**Issue by timotheecour** [duggan/homebrew-protobuf3#1]
```
brew -S protobuf3
Warning: Calling fails_with :llvm is deprecated!
There is no replacement.
/Users/timothee/homebrew/Library/Taps/duggan/homebrew-protobuf3/protobuf3.rb:66:in `<class:Protobuf3>'
Please report this to the duggan/protobuf3 tap!

Warning: Calling fails_with :llvm is deprecated!
There is no replacement.
/Users/timothee/homebrew/Library/Taps/duggan/homebrew-protobuf3/protobuf3.rb:66:in `<class:Protobuf3>'
Please report this to the duggan/protobuf3 tap!

Warning: Calling fails_with :llvm is deprecated!
There is no replacement.
/Users/timothee/homebrew/Library/Taps/duggan/homebrew-protobuf3/protobuf3.rb:66:in `<class:Protobuf3>'
Please report this to the duggan/protobuf3 tap!

Warning: Calling fails_with :llvm is deprecated!
There is no replacement.
/Users/timothee/homebrew/Library/Taps/duggan/homebrew-protobuf3/protobuf3.rb:66:in `<class:Protobuf3>'
Please report this to the duggan/protobuf3 tap!

duggan/protobuf3/protobuf3
```

brew config|grep VERSION
HOMEBREW_VERSION: 1.3.0

**Comment by timotheecour** [comment]
just noticed this formula is deprecated, closing
